import {compute,parseInputs} from './datapath.mjs';
const $=id=>document.getElementById(id);
const initial={q:[1,0,1,1,0,0,1,0],keys:['10110010','10110110','00110011','11100010','01001101','10100000','11010010','00111010'].map(s=>[...s].map(Number)),values:[[1,0,2],[0,2,1],[3,1,-1],[1,-2,0],[-1,1,3],[2,0,1],[0,3,-2],[1,1,1]]};
let input=structuredClone(initial),options={k:4,tile:4,local:2,scale:1,temperature:1},step=5,focus=0,timer=null;
const names=['Query','Match','Select','Softmax','Multiply','Accumulate'];
const n=x=>Math.abs(x)<.00005?'0':Number(x.toFixed(4)).toString();
function result(){return compute(input.q,input.keys,input.values,options);}
function pause(){clearInterval(timer);timer=null;$('flow-run').textContent='▶ Run attention';}
function editors(){$('flow-q').value=input.q.join('');$('flow-keys').value=input.keys.map(r=>r.join('')).join('\n');$('flow-values').value=input.values.map(r=>r.join(', ')).join('\n');for(const key of Object.keys(options))$('flow-'+key).value=options[key];}
function persist(){const p=new URLSearchParams(location.hash.slice(1));p.set('attention',JSON.stringify({input,options}));history.replaceState(null,'','#'+p);}
function draw(){const r=result();$('flow-counter').textContent=`${input.keys.length} stored keys · ${input.q.length} bits · ${r.output.length} output values`;$('flow-query').innerHTML=input.q.map((b,j)=>`<button data-qbit="${j}" aria-label="Input query bit ${j+1}: ${b}" class="${b?'one':''}">${b}</button>`).join('');$('flow-stage-nav').innerHTML=names.map((name,i)=>`<button data-phase="${i}" class="${step===i?'current':step>i?'done':''}">${i+1} ${name}</button>`).join('');
 $('flow-table').style.setProperty('--dims',r.output.length);
 $('flow-table').innerHTML=`<div class="flow-head"><span>BA-CAM · stored K</span><span>Hamming<br>matches</span><span>Local top-${options.local}<br>→ global top-${options.k}</span><span>Sparse<br>softmax</span><span>Value SRAM · BF16 V</span><span>MAC products · αᵢ × Vᵢ</span></div>`+input.keys.map((key,i)=>{
 const local=r.candidates.includes(i),selected=r.selected.includes(i),dim=step>=2&&!selected;
 return `<div class="flow-row ${focus===i?'focused':''} ${dim?'pruned':''}" data-row="${i}"><div class="flow-key"><button class="row-select" data-focus="${i}" aria-label="Trace row ${i+1}">K${i+1}</button><div class="flow-keybits">${key.map((b,j)=>`<button data-keyrow="${i}" data-keybit="${j}" aria-label="Key ${i+1} bit ${j+1}: ${b}" class="${step>=1&&b===input.q[j]?'hit':''}">${b}</button>`).join('')}</div></div><div class="wire-number ${step>=1?'lit':''}">${step>=1?`${r.matches[i]}<small> / ${key.length}</small>`:'·'}</div><div class="flow-gate">${step>=2?`<span class="${selected?'kept':''}">${selected?'PASS →':local?'global drop':'local drop'}</span>`:'·'}</div><div class="wire-number weight ${step>=3&&selected?'lit':''}">${step>=3?n(r.weights[i]):'·'}</div><div class="flow-value">${r.stored[i].map((v,j)=>`<input aria-label="Value row ${i+1} dimension ${j+1}" data-vrow="${i}" data-vdim="${j}" type="number" step="any" value="${v}">`).join('')}</div><div class="flow-products">${r.products[i].map(p=>`<span>${step>=4?n(p):'·'}</span>`).join('')}</div></div>`;
 }).join('');
 $('flow-output').innerHTML=r.output.map((v,j)=>`<div><span>Output [${j}]</span><strong>${step>=5?n(v):'·'}</strong><small>${step>=5?r.selected.map(i=>n(r.products[i][j])).join(' + '):'Σ weighted value contributions'}</small></div>`).join('');
 const i=focus;$('flow-detail').innerHTML=`<b>Trace row ${i+1}</b><span>${input.q.join('')} ⊙ ${input.keys[i].join('')} → <b>${r.matches[i]} matches</b></span><span>logit = ${r.matches[i]} × ${options.scale} / ${options.temperature} = <b>${n(r.logits[i])}</b></span><span>α${i+1} = <b>${n(r.weights[i])}</b>${r.selected.includes(i)?' after sparse softmax':' (pruned)'}</span><span>${n(r.weights[i])} × [${r.stored[i].map(n).join(', ')}] = <b>[${r.products[i].map(n).join(', ')}]</b></span>`;
 $('flow-explain').textContent=[`Your ${input.q.length}-bit query is broadcast to every stored key. Click query or key bits to change the comparison.`,`Each row computes XNOR matches in parallel. The highlighted cells match the query; their sum is the Hamming similarity.`,`Groups of ${options.tile} rows retain their local top-${options.local}. Global top-${options.k} then selects from those candidates. Faded rows do not contribute to the output.`,`For selected rows, αᵢ = exp(logitᵢ − max) / Σ exp(logitⱼ − max). Pruned rows have zero weight. The weights sum to ${r.weights.reduce((a,b)=>a+b,0).toFixed(6)}.`,`The selected weights address corresponding value rows. Each visible product is αᵢ multiplied by one BF16-stored value component.`,`Sum each product column to obtain the output vector. This is one query and one attention head, with all selected value contributions shown.`][step];
 $('flow-prev').disabled=step===0;$('flow-next').disabled=step===5;persist();
}
function apply(){pause();try{const proposed=parseInputs($('flow-q').value,$('flow-keys').value,$('flow-values').value);const opts=Object.fromEntries(Object.keys(options).map(k=>[k,Number($('flow-'+k).value)]));compute(proposed.q,proposed.keys,proposed.values,opts);input=proposed;options=opts;focus=0;step=0;$('flow-error').textContent='';editors();draw();}catch(e){$('flow-error').textContent=e.message;}}
function setup(){
 const root=$('playground');root.innerHTML=`<div class="flow-intro"><div><p class="eyebrow">ONE QUERY · ONE ATTENTION HEAD</p><h2>Your input. Through the whole datapath.</h2><p>Edit Q, K and V. Follow the same row from binary match to its contribution to the output.</p></div><button id="flow-edit">Edit input matrices</button></div><details id="flow-editors"><summary>Custom query, keys and values</summary><div class="flow-edit-grid"><label>Query Q · binary vector<textarea id="flow-q" rows="2" spellcheck="false"></textarea><span>One vector, 1–64 bits.</span></label><label>Keys K · one binary key per line<textarea id="flow-keys" rows="9" spellcheck="false"></textarea></label><label>Values V · one numeric row per key<textarea id="flow-values" rows="9" spellcheck="false"></textarea><span>Separate components with spaces or commas.</span></label></div><div class="flow-settings"><label>Rows per tile<input id="flow-tile" type="number" min="1" max="32"></label><label>Local top-k<input id="flow-local" type="number" min="1" max="32"></label><label>Global top-k<input id="flow-k" type="number" min="1" max="32"></label><label>Score scale<input id="flow-scale" type="number" min="0.001" step="any"></label><label>Temperature<input id="flow-temperature" type="number" min="0.001" step="any"></label><button id="flow-apply" class="primary">Apply Q, K, V</button></div><p id="flow-error" role="alert"></p></details><div class="flow-workbench"><div class="flow-top"><div><p class="eyebrow">SEARCH QUERY Q</p><div id="flow-query"></div></div><div class="flow-buttons"><button id="flow-run" class="primary">▶ Run attention</button><button id="flow-prev">←</button><button id="flow-next">Step →</button><button id="flow-all">Show output</button></div></div><div class="query-broadcast">↓ Broadcast query across BA-CAM rows <span id="flow-counter"></span></div><div id="flow-stage-nav"></div><p id="flow-explain" aria-live="polite"></p><div class="flow-scroll"><div id="flow-table"></div></div><div class="flow-sum">SELECTED ROWS → VALUE READS → BF16 MAC PATH → Σ</div><div id="flow-output"></div><div id="flow-detail"></div></div><p class="note">Editable functional example of CAMformer’s association → hierarchical selection → sparse softmax → value aggregation. The paper configuration uses 64-bit Q/K, 16-row tiles, local top-2, global top-32 and eight BF16 MACs. Values here are rounded to BF16 storage; weights, products and sums use JavaScript precision. Score scale and temperature are illustrative controls, not learned HAD parameters. This is not an analog or cycle-exact simulation.</p>`;
 try{const saved=JSON.parse(new URLSearchParams(location.hash.slice(1)).get('attention'));if(saved){parseInputs(saved.input.q.join(''),saved.input.keys.map(r=>r.join('')).join('\n'),saved.input.values.map(r=>r.join(',')).join('\n'));compute(saved.input.q,saved.input.keys,saved.input.values,saved.options);input=saved.input;options=saved.options;}}catch{}
 editors();draw();$('flow-edit').onclick=()=>{$('flow-editors').open=!$('flow-editors').open;};$('flow-apply').onclick=apply;
 root.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const d=b.dataset;if(d.qbit!==undefined){pause();input.q[+d.qbit]^=1;editors();draw();}if(d.keyrow!==undefined){pause();input.keys[+d.keyrow][+d.keybit]^=1;focus=+d.keyrow;editors();draw();}if(d.focus!==undefined){focus=+d.focus;draw();}if(d.phase!==undefined){pause();step=+d.phase;draw();}});
 root.addEventListener('input',e=>{const d=e.target.dataset;if(d.vrow!==undefined){const v=e.target.valueAsNumber;if(!Number.isFinite(v)||Math.abs(v)>1e6){e.target.setCustomValidity('Enter a finite number between −1,000,000 and 1,000,000.');e.target.reportValidity();return;}e.target.setCustomValidity('');pause();input.values[+d.vrow][+d.vdim]=v;focus=+d.vrow;editors();const r=result();document.querySelectorAll('#flow-table .flow-products').forEach((row,i)=>{row.innerHTML=r.products[i].map(p=>`<span>${step>=4?n(p):'·'}</span>`).join('');});$('flow-output').innerHTML=r.output.map((v,j)=>`<div><span>Output [${j}]</span><strong>${step>=5?n(v):'·'}</strong><small>${step>=5?r.selected.map(i=>n(r.products[i][j])).join(' + '):'Σ weighted value contributions'}</small></div>`).join('');$('flow-detail').textContent=`Edited value row ${focus+1}: BF16 stored [${r.stored[focus].map(n).join(', ')}], weight ${n(r.weights[focus])}, products [${r.products[focus].map(n).join(', ')}].`;persist();}});
 $('flow-prev').onclick=()=>{pause();step=Math.max(0,step-1);draw();};$('flow-next').onclick=()=>{pause();step=Math.min(5,step+1);draw();};$('flow-all').onclick=()=>{pause();step=5;draw();};$('flow-run').onclick=()=>{if(timer){pause();return;}step=0;draw();$('flow-run').textContent='Pause';timer=setInterval(()=>{step++;draw();if(step===5)pause();},1300);};
 document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>{pause();document.body.classList.toggle('attention-first',b.dataset.tab==='playground');}));
 $('reset').addEventListener('click',()=>{if(document.body.classList.contains('attention-first')){pause();input=structuredClone(initial);options={k:4,tile:4,local:2,scale:1,temperature:1};step=5;focus=0;editors();draw();}});
 window.addEventListener('hashchange',()=>{if(new URLSearchParams(location.hash.slice(1)).get('tab')==='playground')draw();});
 document.body.classList.toggle('attention-first',new URLSearchParams(location.hash.slice(1)).get('tab')==='playground');
 window.addEventListener('attention-view',()=>{document.body.classList.add('attention-first');draw();});
}
setup();
