[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "camformer"
version = "1.0.0"
authors = [
  { name="Tergel Molom-Ochir" },
]
description = "Event-driven architectural simulator for CAMformer: Binary Associative Memory Is All You Need."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "numpy>=1.21.0",
    "matplotlib>=3.3.0"
]

[project.optional-dependencies]
test = [
    "pytest>=7.0.0"
]
